//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BladikAlbik.Bdshka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemplar
    {
        public int ID_ex { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_type { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Types Types { get; set; }
    }
}
